### PR TITLE
bump sidekiq dependency 3

### PR DESCRIPTION
**Pull request by sbounmy**
Hello,

sidekiq 3.x have been released 4 months ago, time to bump dependency :+1: 

Cheers,
Stephane.

### CODE REVIEW

**Comment by olance** [comment]
can someone please merge this?
@wr0ngway  or @adstage-david / @therabidbanana ?

Thanks!

**Comment by wr0ngway** [comment]
Sorry, I haven't used sidekiq in a couple of years.  Anyone want to volunteer to take over maintenance of this gem?

**Comment by adstage-david** [comment]
We haven't used this gem ourselves for almost a year now - an incompatibility with sidekiq-pro reliable fetch cropped up andt made it impossible for us to continue using this gem. I'll hit the merge button and roll a release since it looks green on travis, but definitely would be good to find someone else interested in maintenance of the project.

**Comment by adstage-david** [comment]
Ah, nevermind, guess I never got push access anyway - the code is committed and release is ready to go though @wr0ngway

**Pull request merged**
